kind: pipeline
type: docker
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./m2
  - name: set version
    image: maven:3.8-openjdk-17
    commands:
      - mvn versions:set -DnewVersion=${DRONE_TAG} -Dmaven.repo.local=./m2
      - mvn versions:commit -Dmaven.repo.local=./m2
    when:
      event: tag

  - name: build
    image: maven:3.8-openjdk-17
    commands:
      - mvn clean install  -Dmaven.repo.local=./m2
      - mvn clean install -pl web -Dmaven.repo.local=./m2
      - cp web/target/Homedash-*.jar web/docker/
      - echo "latest,$(mvn help:evaluate -Dexpression=project.version -q  -DforceStdout -Dmaven.repo.local=./m2)" > .tags
      - cat .tags


  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./m2

  - name: publish new version
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - '${DRONE_COMMIT}'
        - '${DRONE_TAG}'
        - latest
      repo: gonzague/homedash
      context: web/docker
      dockerfile: web/docker/Dockerfile
    when:
      event: tag

  - name: publish commit
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - '${DRONE_COMMIT}'
      repo: gonzague/homedash
      context: web/docker
      dockerfile: web/docker/Dockerfile
    when:
      event:
        exclude:
          - tag

  - name: git hub release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files: web/target/Homedash-*.jar
    when:
      event: tag
trigger:
  branch:
    - master
  event:
    - push

volumes:
  - name: cache
    host:
      path: /tmp/cache
