kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: maven:3.6.3
    commands:
      - mvn clean install
      - mvn clean install -pl web
      - cp web/target/Homedash-*.jar web/docker/
      - echo "latest,$(mvn help:evaluate -Dexpression=project.version -q  -DforceStdout)" > .tags
      - cat .tags
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: gonzague/homedash
      force_tags: true
      context: web/docker
      dockerfile: web/docker/Dockerfile
trigger:
  branch:
    - master
  event:
    - push
